name: Trigger auto deployment for rg-backend-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/rg-backend-app-AutoDeployTrigger-8dbd4588-c52d-45b9-9384-18f5243260ac.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.RGBACKENDAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.RGBACKENDAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.RGBACKENDAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: docker.io
          registryUsername: ${{ secrets.RGBACKENDAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.RGBACKENDAPP_REGISTRY_PASSWORD }}
          containerAppName: rg-backend-app
          resourceGroup: recipe-generator
          imageToBuild: ili16/rg-backend-app:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


